var data={
    "resultcode": "200",
    "reason": "Success",
    "result": {
        "data": [{
            "id": "72",
            "title": "宫保鸡丁",
            "tags": "川菜;家常菜;麻辣;炒;夏季;传统",
            "imtro": "宫保鸡丁，川菜传统名菜，一般认为由清朝四川总督丁宝桢所创。 现在大大小小的中餐馆中，“宫保鸡丁”这道菜可谓司空见惯。至于有些菜单上写成了宫爆鸡丁，是有人认为烹制方法为“爆炒”，其实这是一种误解，没有弄清楚“宫保鸡丁”的由来。 据传，丁宝桢对烹饪颇有研究，喜欢吃鸡和花生米，并尤其喜好辣味。他在四川总督任上的时候创制了一道将鸡丁、红辣椒、花生米下锅爆炒而成的美味佳肴。 这道美味本来只是丁家的“私房菜”，但后来越传越广，尽人皆知。但是知道它为什么被命名为“宫保”的人就不多了。 时过境迁，很多人已不知“宫保”为何物，就想当然地把“宫保鸡丁”写成了“宫爆鸡丁”，虽一字之差，但却改变了纪念丁宝桢的初衷！ 宫保鸡丁是由鸡丁、干辣椒、花生米等炒制而成，鸡肉的鲜嫩配合花生的香脆，入口鲜辣酥香。",
            "ingredients": "鸡脯肉,400g;黄瓜,100g;熟花生,100g",
            "burden": "油,适量;盐,适量;葱,适量;料酒,适量;生抽,适量;花椒,适量;醋,适量;糖,适量;水淀粉,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/1\/72_623523.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/1\/72_215ffa92c8d83d1c.jpg",
                "step": "1.原料"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/1\/72_56cc6d7217e01da5.jpg",
                "step": "2.黄瓜切丁、葱要切成小段，干辣椒剪去两头，去除辣椒籽"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/1\/72_3563ebeeca65a60c.jpg",
                "step": "3.鸡胸肉切丁，放生抽、盐、料酒码味，用水淀粉拌匀"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/1\/72_14fd33a818d81569.jpg",
                "step": "4.在小碗中调入酱油、盐、白砂糖和料酒，混合均匀制成调味料汁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/1\/72_93e1093ff3ac3baa.jpg",
                "step": "5.锅中留底油，烧热后将花椒和干辣椒放入，用小火煸炸出香味，随后放入大葱段"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/1\/72_312430a078c7c1aa.jpg",
                "step": "6.放入鸡丁，放1汤匙料酒，炒到鸡肉变色"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/1\/72_c78766399aa08999.jpg",
                "step": "7.最后调入料汁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/1\/72_57318d2780ec0e71.jpg",
                "step": "8.再放入黄瓜丁、熟花生米，翻炒均匀"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/1\/72_45d759ef78d8d275.jpg",
                "step": "9.水淀粉勾芡，即可"
            }]
        }, {
            "id": "162",
            "title": "宫保鸡丁",
            "tags": "川菜;家常菜;烧;黔菜",
            "imtro": "有点麻、有点辣，嫩滑的鸡肉、脆脆的花生···宫保鸡丁——口感丰富，是超级给力的下饭菜！ 我在家经常会做，有时候是自己准备其中的各种材料，但有时候也会犯懒，就用超市买来的现成的调料包来做，只要一包调一调，炒一炒，在家也能做出可以媲美饭店的经典菜式喽！ 我更偏爱用鸡腿肉来做这道经典的宫保鸡丁，上过浆、滑过油的鸡腿丁非常嫩滑，嚼起来更有弹性，口感要比鸡胸好很多！ 如果想更偷懒，也可以使用那种市售的麻辣花生。",
            "ingredients": "鸡腿肉,400g;花生,150g",
            "burden": "干红辣椒,适量;姜,适量;蒜,适量;宫保鸡丁调料,1袋;料酒,适量;水淀粉,适量;蛋清,适量;盐,适量;大葱,100g",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/1\/162_744604.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/162_718f48c17566ff16.jpg",
                "step": "1.生花生米泡开水中10分钟。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/162_3e0c76a085f2ab53.jpg",
                "step": "2.去掉外表的红衣。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/162_2591a3890efdd6bf.jpg",
                "step": "3.将去红衣的花生米冷油下锅，小火慢慢炸至酥脆，盛出沥干晾凉备用"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/162_95634fb0331aab59.jpg",
                "step": "4.准备宫保鸡丁调料一包；干红辣椒适量剪成小段；大葱切粒、姜蒜切小片（喜欢更麻辣一点的可以再准备少许花椒）。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/162_4bd44e67283c5673.jpg",
                "step": "5.将宫保鸡丁调料一包倒在碗中加入60ml水调匀备用。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/162_7492f93f6283b306.jpg",
                "step": "6.将鸡腿肉去皮切成小丁，加入少许料酒、盐、湿淀粉和少许蛋清抓拌均匀后腌制10分钟。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/162_c75535c93399246d.jpg",
                "step": "7.炒锅烧热后加油适量，马上下入鸡肉丁，用筷子划散，见鸡肉变白色后盛出控净油分。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/162_4cbbc7e5f9e36a4e.jpg",
                "step": "8.倒出锅中的油，只留少许，依次加入干红辣椒、姜、蒜、大葱丁，煸炒出香味。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/162_1035328c99bbcbfe.jpg",
                "step": "9.下入划过油的鸡肉丁翻炒"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/162_1dea47d652297381.jpg",
                "step": "10.加入调好的味好美宫保鸡丁调料汁，快速翻炒"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/162_de10e00cca9e015c.jpg",
                "step": "11.见调料汁变浓稠并均匀的包裹在食材上后，加入炸好的花生米，关火。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/162_b2de53526e63d071.jpg",
                "step": "12.迅速翻炒均匀即可装盘。"
            }]
        }, {
            "id": "177",
            "title": "木耳宫保鸡丁",
            "tags": "家常菜;麻辣;炒;母亲节",
            "imtro": "清清楚楚记得小时候妈妈常与阿姨们厨艺交流。其中有一道印象最深，那就是去皮花生米与肉丁一起炒，一个焦脆，一个软滑；一个白黄，一个酱红；略带点辣味，我很是喜爱。不过不知道叫啥个名子，直到来到了挪威才知晓，差不多每一个中国餐馆都有这道菜“宫保鸡丁”。在餐馆打工时就见到一位年轻的挪威人差不多每周都来买，而且只点这一道菜，他认为这就是“天上人间”——中国菜的全部。 我也不知怎样做才是正宗的，只知从小到大受到妈妈的影响，注重色香味。因此就加了一点黑色的木耳，这样在色彩上除白黄和酱红，又加了一个亮黑，最后来点蒜苗点缀，看上去很是喜人，老公说配中国白酒最合适不过了。 木耳，我常常用来配菜，这还是从妈妈给我看了一本老年人手抄手册开始的。上面记述了一个真人故事，一位老人在美国因洋餐的油脂过多摄入，血脂偏高，可是回国几月，再检查一切正常了，只因他常食木耳的原因。 现在玩美食常常注重营养学，木耳除降脂以外，可养血驻颜，防治缺铁性贫血；还可对付粉尘污染，这一点最感兴趣。 妈妈说现在到处灰灰的，根本就不感出门，那就给她老上一盘木耳宫保鸡丁，将红辣椒，整只油煎，然后夹出，因她老不能吃辣，辣子留给爱吃辣的我享用去吧。",
            "ingredients": "鸡胸肉,160g;花生米,60g;泡发木耳,60g",
            "burden": "油,适量;盐,适量;葱,适量;干辣椒,适量;花椒,适量;生抽,适量;老抽,适量;胡椒粉,适量;蛋清,适量;白砂糖,适量;淀粉,适量;大蒜,适量;姜,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/1\/177_265149.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_cab7f86699c90bd1.jpg",
                "step": "1.备好食材：鸡胸肉160克，花生米60克，泡发木耳60克，葱姜蒜、干辣椒和花椒适量。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_62cb7550de78b340.jpg",
                "step": "2.用开水冲泡花生米，剥去外皮。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_1d789cb011ad28a1.jpg",
                "step": "3.木耳切小块。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_dc992906ee6fac89.jpg",
                "step": "4.鸡胸肉切丁，还有木耳和葱姜蒜也切好备用。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_75c859166833a1eb.jpg",
                "step": "5.取一小碗，放入鸡丁，加入老抽、盐、糖、胡椒、淀粉和一勺蛋清，用手抓均。注：用手抓均易入味，食物带有你的体温和心情。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_ed4e394d80df4c0f.jpg",
                "step": "6.调一小碗芡汁：淀粉、生抽和水或高汤。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_7f12be59df0118eb.jpg",
                "step": "7.冷锅冷油下花生米。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_91dcf3bde3f2d419.jpg",
                "step": "8.中火炒至浅焦黄色，盛到大点的盘子里，方便散热。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_2e7ea02440ff74e1.jpg",
                "step": "9.用原油下干辣椒和花椒，还是中火，炸到香，将辣椒夹出，留给能吃辣的享用。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_911469dc5eadff06.jpg",
                "step": "10.然后下葱姜蒜爆香。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_5d495c2b0a498c90.jpg",
                "step": "11.紧接着下鸡丁。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_430c87596c852479.jpg",
                "step": "12.将鸡丁滑炒变色，下木耳。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_08c512f88917666f.jpg",
                "step": "13.当木耳炒的有点炸锅时，倒入芡汁。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/2\/177_9752b6dd64491cf0.jpg",
                "step": "14.翻均，下炸好的花生米，快速拌均即可起锅。"
            }]
        }, {
            "id": "227",
            "title": "宫保鸡丁",
            "tags": "家常菜;咸香;10-20分钟;宴请;朋友聚餐;1-2人;锅子;其他工艺",
            "imtro": "上次提起我老公第一次到我家，我为了显示一下，特地做了这道菜，当然那时的我做这菜可是用了半天的时间啊，结果很难吃，好在我老公为了给我面子，总是拼命的吃。今天再做这菜时，味道自然好，老公更是赞不绝口了。。 有朋友说了,宫保鸡丁是没葱的,哎,别人送我点葱我就想着好看就用上了,亲们可别学我啊...",
            "ingredients": "鸡胸肉,250g;花生米,50g",
            "burden": "淀粉,5g;酱油,15g;白糖,10g;醋,10g;料酒,10g;生姜,3片;葱,5g;蒜,5g;辣椒,２个",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/1\/227_534950.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/3\/227_05046e040e910800.jpg",
                "step": "1.将酱油10克，白糖10克，醋10克，料酒10克调汁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/3\/227_3bbc221c25d00a5b.jpg",
                "step": "2.准备生姜三片切末，葱5克切段，蒜5克切末，辣椒2个切段"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/3\/227_59a79e84da2d4c5b.jpg",
                "step": "3.鸡肉切丁加入淀粉5克，酱油5克，色拉油10克搅拌"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/3\/227_f4bc658a315d6e9b.jpg",
                "step": "4.花生米加点油用烤箱烤熟"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/3\/227_243e1dbf47b15c15.jpg",
                "step": "5.锅里油热，先下入鸡丁过熟"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/3\/227_7d024a3071f0bc45.jpg",
                "step": "6.取出"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/3\/227_9d732f4f553c4add.jpg",
                "step": "7.再下入生姜末，，蒜末，辣椒段炸有香味"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/3\/227_e62b7b6a72de5043.jpg",
                "step": "8.倒入鸡丁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/3\/227_87eda69d68a1e8ea.jpg",
                "step": "9.下入调料"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/3\/227_17208f339bd8dbfb.jpg",
                "step": "10.最后加入花生米和葱，关火搅拌即可。此菜特点，鸡丁软嫩，花生香脆。如果喜欢咸点可以在调汁中加入２克盐"
            }]
        }, {
            "id": "433",
            "title": "麻辣宫保鸡丁",
            "tags": "家常菜;10分钟内;烧;1-2人;锅子;川菜辣够味",
            "imtro": "吃黄飞红花生上瘾了。欣和送的10袋早已经吃完了，又买了5袋。得亏是冬天，要不非得上火不可。也攒下了不少里面的麻椒和辣椒。由于受黄飞红的影响，最近非常喜欢吃麻辣的食物了，做什么都想放上一些麻 辣椒。也搭上用黄飞红里面的麻辣椒炒菜非常香，那个麻辣的味道十分正宗。麻麻辣辣的很过瘾。麻辣宫保鸡丁是在原有的宫保鸡丁里多多添加了麻椒和辣椒，是一道超级下饭菜。",
            "ingredients": "鸡腿,300g;花生,50g;大葱,50g",
            "burden": "油,适量;盐,适量;麻辣椒,适量;糖,适量;醋,适量;酱油,适量;辣椒面,适量;鸡精,适量;淀粉,适量;料酒,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/1\/433_308826.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/5\/433_a2eaf708c6ab96c7.jpg",
                "step": "1.把鸡腿洗净去骨。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/5\/433_afb47a4dfef97e85.jpg",
                "step": "2.鸡腿肉切成丁，加入盐 料酒 淀粉上浆备用。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/5\/433_7d4088db2a299c99.jpg",
                "step": "3. 把大葱切成段，准备好花生米。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/5\/433_3626980c4ff15e74.jpg",
                "step": "4.取一碗加入清水 淀粉 糖 醋 酱油 辣椒面勾兑成料汁。 。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/5\/433_8f55b4fa9484e08a.jpg",
                "step": "5. 准备好黄飞红的麻椒和辣椒。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/5\/433_5f033635f579ee23.jpg",
                "step": "6. 锅中放油，烧热，下入鸡丁煸炒至变色"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/5\/433_3a0f190fca61b974.jpg",
                "step": "7.放入麻椒和辣椒，小火炒出红油。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/5\/433_8b9e378e1b847266.jpg",
                "step": "8. 倒入料汁，烧至汤汁粘稠，使鸡丁均匀的裹上料汁。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/5\/433_091df36fd0e842f6.jpg",
                "step": "9.下入花生米和葱段，快速翻炒均匀，加入鸡精调味即可。"
            }]
        }, {
            "id": "558",
            "title": "宫保鸡丁",
            "tags": "川菜;家常菜;炒;白领;午餐;下酒菜",
            "imtro": "宫保鸡丁，又称宫爆鸡丁，川菜系中的传统名菜，由鸡丁、干辣椒、花生米等炒制而成。由于其入口鲜辣，鸡肉的鲜嫩配合花生的香脆，广受大众欢迎。 关于“宫保鸡丁”的来历，我想知道的人不多，包括那些把它纳入其菜单招揽食客的餐馆老板。说起“宫保鸡丁”，不得不道出一段耐人寻味的典故： 熟悉晚清历史的人，对丁葆桢（生前封“太子少保”,尊称为丁宫保）其人，应该不陌生，其智斩慈禧宠臣安德海的胆量和气魄一直被后人传为佳话。话说，当年丁葆桢由山东调任四川巡抚，时直都江堰水患，新官上任三把火，遂前往视察。由于耽误了吃中午饭的时间，不得不在道上一家小餐馆进餐，不巧哪天刚好很多菜样已卖完，无菜可炒。众人饥肠辘辘，等不急去别的餐馆，就用鸡肉等几种原料，快炒之。丁葆桢吃着觉得味道鲜美，很是满意，“宫保鸡丁”由此大出其名。",
            "ingredients": "鸡胸肉,1块;花生米,80g;荷兰黄瓜,1个;葱白,1根",
            "burden": "花椒,5g;干辣椒,2个;白糖,12g;米醋,15ml;生抽,10ml;玉米淀粉,4g;盐,3g;料酒,20ml;水,适量;橄榄油,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/1\/558_960743.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_a997ec846bcca560.jpg",
                "step": "1.准备好主要食材。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_37b58b742547357c.jpg",
                "step": "2.鸡胸肉洗净，切成大拇指甲盖大小的丁儿。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_3919c9fdaf9115ee.jpg",
                "step": "3.葱白切成和鸡肉丁差不对大小的段儿。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_a94af969663b95ff.jpg",
                "step": "4.干辣椒切大小一致的段儿。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_a17a214f03882940.jpg",
                "step": "5.荷兰黄瓜切成大小一致的丁儿。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_dfc7ed2ef967b516.jpg",
                "step": "6.将切好的鸡肉丁中加1g盐、10ml料酒、2g玉米淀粉和少许水。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_f5d324a6cd321a9a.jpg",
                "step": "7.用手充分抓匀，腌15分钟。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_08aae00322eb891d.jpg",
                "step": "8.将剩余的盐、料酒、玉米淀粉和生抽、白糖、米醋、适量的水，调成调料汁待用。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_3c36c8d14630d6d4.jpg",
                "step": "9.炒锅置于火上，倒入比平时炒菜多一些的橄榄油。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_f3353b395cd5f8c3.jpg",
                "step": "10.六成热时放入花椒、干辣椒，煸炒出香味儿。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_7bea273c8fff7567.jpg",
                "step": "11.放入鸡丁滑炒至变色。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_2456ccb9484a3c2c.jpg",
                "step": "12.放入葱白段儿炒出香味。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_17c29fc7810eec65.jpg",
                "step": "13.倒入调料汁。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_eb13310367054849.jpg",
                "step": "14.过半分钟后倒入黄瓜丁，用铲子翻炒半分钟。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/6\/558_6eb853ea52dc467a.jpg",
                "step": "15.待收汁时倒入油炸花生米，翻拌均匀即可盛出。"
            }]
        }, {
            "id": "1008",
            "title": "宫保鸡丁",
            "tags": "川菜;热菜;夏季;香辣;快手菜;炒锅",
            "imtro": "宫保鸡丁是川菜传统名菜，现在有的饭店称为宫爆鸡丁，这是不对的。据说这道菜由清朝四川总督丁宝桢所创，让家厨用花生米、干辣椒和嫩鸡肉炒制鸡丁，很受大家欢迎。所谓“宫保”是丁宝桢的荣誉官衔，他被朝廷封为“太子少保”，人称“丁宫保”。 这道菜制作的关键是如何把握好鸡肉的成熟度，吃起来口感滑嫩香辣而不柴。鸡肉可以选择鸡胸肉或者鸡腿肉。",
            "ingredients": "鸡胸肉,300g;花生米,50g;黄瓜,50g;干辣椒,2个",
            "burden": "白糖,2大勺;盐,1小勺;花椒,1小勺;生姜,10g;大葱,30g;大蒜,10g;生抽,1小勺;醋,2小勺;味精,1\/4小勺;料酒,1小勺;鸡蛋清,半个;干淀粉,2小勺;胡椒粉,1\/4小勺",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/1\/1008_908222.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/11\/1008_da469311f0779ff1.jpg",
                "step": "1.所有材料准备好。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/11\/1008_bbc74a3dbe5ba63b.jpg",
                "step": "2.鸡肉切成1厘米见方的块，加入1茶匙干淀粉、1\/4茶匙盐、料酒、蛋清、胡椒粉。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/11\/1008_0ce4d6125afe0fbd.jpg",
                "step": "3.用手抓匀，腌制5分钟。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/11\/1008_10a11f747ac1408c.jpg",
                "step": "4.黄瓜切丁，大葱、干辣椒切段，生姜切粒，大蒜切片。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/11\/1008_5675def3fcd16ff0.jpg",
                "step": "5.花生米放入微波炉中高火打2个1分钟，中间取出翻动一下，晾凉后搓去外皮。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/11\/1008_f2df5bf7b74c72d0.jpg",
                "step": "6.把生抽、醋、糖、味精、剩余的干淀粉和盐放入小碗中，加2汤匙水调匀。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/11\/1008_43df6b392230d0cc.jpg",
                "step": "7.锅内放入少许油烧至4成热，放入鸡丁滑散，炒至表面变白盛出。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/11\/1008_4a1f03058f1ca582.jpg",
                "step": "8.锅内留底油，先放入花椒爆香，再放入葱姜蒜和干辣椒炒出香味。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/11\/1008_7dd90d3ff6edddaf.jpg",
                "step": "9.放入鸡丁略炒。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/11\/1008_359d6e424ee83b65.jpg",
                "step": "10.再放入黄瓜丁翻炒均匀。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/11\/1008_9eb407690ccc9c4f.jpg",
                "step": "11.调好的味汁再次搅拌均匀淋入锅内，大火快速炒匀。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/11\/1008_56e39f990110d7ab.jpg",
                "step": "12.最后放入花生米翻炒均匀即可。"
            }]
        }, {
            "id": "1149",
            "title": "宫保鸡丁",
            "tags": "川菜;热菜;健脾开胃;增肥;骨质疏松;咸;炒;冬季;香辣;补钙;快手菜;补中益气;健脾;补虚;健脾胃;增高;脾虚",
            "imtro": "宫保鸡丁每个人做出来的口味都不太一样，就连酒店的厨师做出来也各有风味，今天我在家山寨一把，味道还有点像哈~鸡肉蛋白质的含量比例较高，而且很容易被人体吸收利用，有增强体力、强壮身体的作用。",
            "ingredients": "鸡肉,200g;花生米,50g;大葱,1\/2根",
            "burden": "油,适量;盐,适量;味精,适量;酱油,适量;糖,适量;姜蒜辣椒,适量;水淀粉,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/2\/1149_109862.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/12\/1149_dbb364926add907b.jpg",
                "step": "1.鸡胸肉切丁，用料酒，白芝麻，水淀粉腌制一下"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/12\/1149_db564b423a893118.jpg",
                "step": "2.熟花生米搓去外皮"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/12\/1149_3bd67de6ff082070.jpg",
                "step": "3.然后准备料汁，将蒜辣椒切丁放小碗里"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/12\/1149_fb9596730715e83c.jpg",
                "step": "4.加入酱油，糖，味精，盐，水淀粉调成汁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/12\/1149_f23f65c9e076dd34.jpg",
                "step": "5.锅里油烧热后加入大葱翻炒"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/12\/1149_bbc73ecb1bad3b57.jpg",
                "step": "6.接着倒入鸡肉丁翻炒"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/12\/1149_590730c492af25e5.jpg",
                "step": "7.炒到鸡肉变成白色后，倒入料汁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/12\/1149_9279826e7eb28bb6.jpg",
                "step": "8.最后倒入花生米翻炒均匀就可以了"
            }]
        }, {
            "id": "7341",
            "title": "宫保鸡丁",
            "tags": "川菜;咸香;营养;酥脆;下饭菜;鲜辣",
            "imtro": "这是一道川菜中的保留家常菜，由鸡丁、干辣椒、花生米等炒制而成。由于其入口鲜辣，鸡肉的鲜嫩配合花生的香脆，深受大众喜欢。 吃鸡肉不光是为了好吃而且还有营养，鸡肉里面脂肪的含量比猪肉少很受大家欢迎。",
            "ingredients": "鸡脯肉,250g;花生米,200g",
            "burden": "葱,适量;盐,适量;干辣椒,适量;花椒,适量;蒜,适量;酱油,适量;醋,适量;料洒,适量;鲜汤,适量;姜,适量;糖,适量;红薯淀粉,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/8\/7341_887885.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_968bd71202c2fa72.jpg",
                "step": "1.姜、蒜去皮切片"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_dd93a188e44a774e.jpg",
                "step": "2.葱白切成颗粒状"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_f5ca664530d3fb1a.jpg",
                "step": "3.干辣椒去蒂去籽，切成1厘米长的节"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_ef7270a4ba2b924f.jpg",
                "step": "4.鸡肉拍松，再用刀改成小丁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_785f96738e854501.jpg",
                "step": "5.用盐、酱油、料酒红薯淀粉拌匀上浆去腥"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_19ad146b3d63da19.jpg",
                "step": "6.花生米洗净，放入油锅炸脆"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_1fd0e40afc3d4315.jpg",
                "step": "7.捞出冷却。火候控制好，炸过火了花生吃起来有一些苦味。(花生可以去皮，也可以不去，花生的红皮有很好的补血功效，对人体很有好处，但为了做菜好看，很多朋友都去掉了那层红皮。）"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_d9911fd9d88169e8.jpg",
                "step": "8.烧热锅，下油，烧热将鸡肉入锅炒到变色捞出"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_5a327b20d4eacce7.jpg",
                "step": "9.再起锅放油烧热后将姜，蒜"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_092e6dfafb5e7c61.jpg",
                "step": "10.炒出香味后放入干辣椒炒至棕红色"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_236f971497041561.jpg",
                "step": "11.再下花椒"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_8c2660df6f712e8a.jpg",
                "step": "12.随即下入炒变色的鸡丁炒散"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_c3857bc870c028b9.jpg",
                "step": "13.加入调味汁翻炒"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7341_f6e17f5bbc1a15a6.jpg",
                "step": "14.起锅前倒入炸好的花生米，翻炒收汁起锅装盘"
            }]
        }, {
            "id": "7357",
            "title": "宫保鸡丁",
            "tags": "川菜;麻辣;炒;冬季;炒锅",
            "imtro": "宫保鸡丁是经典家常菜。做法也被演绎成了多个版本。小二也试着做了一次。在公交车上学习来的做法。宫保鸡丁源于清代的重臣丁宝桢，因其曾官至太子保，而得名宫保鸡丁。",
            "ingredients": "鸡胸脯肉,250g;胡萝卜,100g;花生,100g",
            "burden": "油,适量;盐,适量;淀粉,适量;糖,适量;醋,适量;料酒,适量;葱,适量;花椒,适量;十三香,适量;辣椒,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/8\/7357_796704.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7357_d88f7e05fcc805b6.jpg",
                "step": "1.花生炒熟，晾凉"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7357_88fe532c1c2da44a.jpg",
                "step": "2.鸡肉切丁，用淀粉、十香三、料酒腌制"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7357_c1026b98121bebf0.jpg",
                "step": "3.胡萝卜切丁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7357_951794c37f5511ce.jpg",
                "step": "4.大葱切段"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7357_4f9d13ce155791b6.jpg",
                "step": "5.准好花椒和干辣椒"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7357_96c2f30294ed86af.jpg",
                "step": "6.做好调味汁：糖、醋、盐、淀粉"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7357_475132a0b5b8635c.jpg",
                "step": "7.锅中放油，先把鸡肉放到锅里滑熟"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7357_481bc8790123a6eb.jpg",
                "step": "8.锅中放油，加入花椒、干辣椒、胡萝卜、葱段炒香"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7357_f0ee11038a66f1dc.jpg",
                "step": "9.加入滑熟的鸡丁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7357_2b39e9d8b718e31c.jpg",
                "step": "10.加入6步调味汁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/74\/7357_1df91e2cfb210529.jpg",
                "step": "11.加入炒好的花生，翻炒均匀即可"
            }]
        }, {
            "id": "7402",
            "title": "宫保鸡丁",
            "tags": "川菜;家常菜;咸香;10-20分钟;宴请;朋友聚餐;1-2人;锅子;其他工艺",
            "imtro": "宫保鸡丁由鸡丁、干辣椒、花生米等炒制而成。其入口鲜辣，鸡肉的鲜嫩配合花生的香脆，深受大家的喜欢。",
            "ingredients": "鸡脯肉,200g",
            "burden": "油,适量;盐,适量;葱,适量;辣椒,适量;胡萝卜,适量;花生米,适量;淀粉,适量;料酒,适量;酱油,适量;白糖,适量;醋,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/8\/7402_732075.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7402_f9966bfec2e3eddd.jpg",
                "step": "1.准备材料鸡脯肉、花生米、胡萝卜、葱。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7402_752438b975bcf051.jpg",
                "step": "2.鸡脯肉切小丁。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7402_1a57be1f03f25dec.jpg",
                "step": "3.胡萝卜洗干净也切成小丁。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7402_ceacd469af5e0057.jpg",
                "step": "4.干辣椒和葱切小段。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7402_bb05e38cabc001cd.jpg",
                "step": "5.肉丁加淀粉、料酒、酱油腌制一会。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7402_ff2923cb579edcd6.jpg",
                "step": "6.用料酒、白糖、醋、酱油调成料汁。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7402_ec2abbb29a23a918.jpg",
                "step": "7.凉油下锅把花生米炸至酥香盛出备用。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7402_1748a68429a72f89.jpg",
                "step": "8.锅中放油烧热，放入腌制好的鸡丁，翻炒至肉色变白盛出备用。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7402_87db07ccaa5f552c.jpg",
                "step": "9.锅中留油，放入葱和辣椒煸出香味，放入胡萝卜丁翻炒片刻。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7402_5215111b4b3a0eb4.jpg",
                "step": "10.倒入炒好的鸡丁加盐翻炒均匀。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7402_7803da73803b40b7.jpg",
                "step": "11.转小火，加入调好的料汁。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7402_a47f51af260ad790.jpg",
                "step": "12.再倒入炒好的花生米翻炒均匀即可出锅。"
            }]
        }, {
            "id": "7418",
            "title": "宫保鸡丁",
            "tags": "川菜;家常菜;儿童;炒;夏季;增强抵抗力",
            "imtro": "儿子今天想吃宫保鸡丁，正好家里还有没吃完的炸花生米，就做了这道菜，受到了家人的一致好评，很给力的把这道菜全部吃光，哈哈，开心极了，和大家分享一下。",
            "ingredients": "鸡胸肉,200g;黄瓜,50g;红萝卜,50g",
            "burden": "油,适量;盐,适量;绵白糖,适量;料酒,适量;醋,适量;炸花生,适量;番茄酱,适量;朝天椒,适量;葱蒜末,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/8\/7418_214166.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7418_365a524c5d7cbef3.jpg",
                "step": "1.准备食材"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7418_73fa30531854ae52.jpg",
                "step": "2.鸡胸肉切丁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7418_5cf027191936142d.jpg",
                "step": "3.胡萝卜，黄瓜切成丁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7418_3335e740f6d79d9c.jpg",
                "step": "4.朝天椒、番茄酱准备好"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7418_779139d67c4bb7c3.jpg",
                "step": "5.热锅凉油，把鸡肉滑炒一下"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7418_36c549eb1ca437db.jpg",
                "step": "6.盛出备用"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7418_c0dbdb222bf95d7d.jpg",
                "step": "7.炒锅上火，放入葱蒜末爆香，然后放入辣椒炒一下，再放入番茄酱炒出红油"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7418_7c26e395392cbbc5.jpg",
                "step": "8.调一下味，放入料酒，白糖，盐，和醋调成酸甜汁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7418_28ced0f93d22b2e5.jpg",
                "step": "9.放入鸡肉"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7418_5f78c2e66a2fb606.jpg",
                "step": "10.在把红萝卜放入炒一会"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7418_25b889359fdeaf7b.jpg",
                "step": "11.最后放入黄瓜和熟花生，放点鸡精，出锅装盘"
            }]
        }, {
            "id": "7438",
            "title": "宫保鸡丁",
            "tags": "川菜;宫保鸡丁",
            "imtro": "宫保鸡丁，川菜传统名菜，一般认为由清朝四川总督丁宝桢所创。由鸡丁、干辣椒、花生米等炒制而成。由于其入口鲜辣，鸡肉的鲜嫩配合花生的香脆，广受大众欢迎。尤其在英美等西方国家，宫保鸡丁“泛滥成灾”，几成中国菜代名词，情形类似于意大利菜中的意大利面条。",
            "ingredients": "鸡胸肉,250g;炸花生米,50g",
            "burden": "盐,适量;蒜,10瓣;姜,3片;葱,1段;干红辣椒,4只;花椒,20粒;醋,1大匙;糖,1大匙;酱油,1大匙;料酒,1大匙;淀粉,1匙",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/8\/7438_761986.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7438_0cead20e3bccdd19.jpg",
                "step": "1.准备材料。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7438_95fedaed6a337263.jpg",
                "step": "2.将鸡肉平铺在案板上，用刀背拍松，再用刀在鸡肉上轻切十字花刀。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7438_a5bdc32c670901f3.jpg",
                "step": "3.将鸡肉切成2厘米左右的肉丁，放入碗中，加入1大匙酱油、1匙淀粉、1大匙油拌匀。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7438_6b0586563c0ac114.jpg",
                "step": "4.将干红辣椒剪成2厘米的段，去籽，葱切成1厘米长的段，姜、蒜去皮洗净切片。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7438_26cee041e213401f.jpg",
                "step": "5. 醋1大匙、糖1大匙、酱油1大匙、料酒1大匙、淀粉1匙、盐少量 调和成酱汁待用。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7438_4739f1d495183e99.jpg",
                "step": "6.锅中加入少许油，大火加热到4成热时放入腌好的鸡肉，快速翻炒，看到肉质开始变白后立即捞出。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7438_f4671ab030c2d415.jpg",
                "step": "7.锅中重新加入底油烧到5成热，放入花椒粒炸出香味，然后捞出不用。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7438_2653a47f86aa2429.jpg",
                "step": "8.再放入干辣椒、蒜皮、葱段、姜片炒出香味。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7438_7db063ff8cf19cda.jpg",
                "step": "9.倒入鸡肉。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7438_9b03c0502a0c1c2a.jpg",
                "step": "10.将酱汁搅匀后立即划圈淋入锅中，快速翻炒均匀。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7438_c3edf7828c6cdb7e.jpg",
                "step": "11.看到鸡肉上色后，撒上炸花生米，拌匀后立即出锅。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7438_b9750c4171785e87.jpg",
                "step": "12.香喷喷！"
            }]
        }, {
            "id": "7470",
            "title": "宫保鸡丁",
            "tags": "川菜;家常菜;咸香;下饭;酥脆;增强抵抗力",
            "imtro": "刚刚在好豆学的新菜品，老公赞很好吃。这段时间集中学习鸡肉的多种做法，这个是目前学的最好吃的一种。入口鲜辣，鸡肉的鲜嫩配合花生的香脆，实在美味。",
            "ingredients": "鸡胸肉,250g;花生米,100g",
            "burden": "油,适量;盐,适量;干辣椒,适量;葱白,适量;花椒,适量;姜末,适量;蒜片,适量;生抽,适量;生粉,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/8\/7470_660335.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7470_091f256460d8c83c.jpg",
                "step": "1.葱白切粒，姜切末，蒜瓣切片，干辣椒切小段，还有花椒洗净待用"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7470_924f4d232336d84a.jpg",
                "step": "2.鸡胸肉去皮去骨，洗净切小粒，下少量生抽"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7470_76db3e1d3657b97d.jpg",
                "step": "3.下适量的生粉"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7470_7519d12574a4fac6.jpg",
                "step": "4.筷子搅拌均匀腌制5分钟（我还下了一点油，这样的鸡肉炒起来更嫩滑，可以根据个人喜好选择下或者不下）"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7470_723c2f6d691f677c.jpg",
                "step": "5.锅内下油，炸花生米"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7470_af81c166f647c66e.jpg",
                "step": "6.花生米炸好后取出"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7470_110cddcffe9b37d9.jpg",
                "step": "7.腌制好的鸡肉滑入热油中，炒至变色捞出"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7470_ac6392e6b2291bce.jpg",
                "step": "8.锅内油继续烧热，下蒜片姜末红辣椒和花椒爆香"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7470_91f626c25deb68c0.jpg",
                "step": "9.再下葱白爆香"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7470_6e68db88153b593e.jpg",
                "step": "10.下已经炒变色的鸡丁翻炒均匀"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7470_51400e2fa1db9be5.jpg",
                "step": "11.下适量的盐"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7470_61d9469ddfa2ba1a.jpg",
                "step": "12.下炸好的花生米翻炒均匀后马上出锅"
            }]
        }, {
            "id": "7473",
            "title": "宫保鸡丁",
            "tags": "川菜;家常菜;咸香;10分钟内;宴请;冬季;朋友聚餐;1-2人;锅子;其他工艺",
            "imtro": "在吃方面，我最大的优点就是不挑食，但这个优点也是老妈培养的，因为她总是能把不那么可口的蔬菜做得美味又营养，很小的时候，老妈就从菜谱里翻出这道菜给我们做，以至于我对胡萝卜很是情有独钟，长大了，也可以做出来给妈妈吃了",
            "ingredients": "花生米,100g;青椒,100g;胡萝卜,120g;鸡胸肉,100g",
            "burden": "盐,适量;味精,适量;食用油,适量;醋,适量;白糖,适量;淀粉,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/8\/7473_545850.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7473_65e59a59b56408c0.jpg",
                "step": "1.胡萝卜切丁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7473_9155979fb91b6273.jpg",
                "step": "2.青椒切丁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7473_64d87261c58a76fc.jpg",
                "step": "3.鸡胸肉切丁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7473_51cf582bb6e97188.jpg",
                "step": "4.鸡胸肉里加适量淀粉"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7473_f801a39951e74451.jpg",
                "step": "5.锅里热油，先把花生米倒进去翻炒至变色后捞出"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7473_17364dd152f14a10.jpg",
                "step": "6.用锅里的底油把鸡肉炒熟，盛出备用"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7473_cfdeb88560d78af5.jpg",
                "step": "7.起锅热油，葱花爆香后倒入胡萝卜丁翻炒"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7473_765c0671d112711e.jpg",
                "step": "8.再把青椒块放进去一起翻炒"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7473_2e7adea6ea3117e1.jpg",
                "step": "9.然后把鸡丁放进锅里一起翻炒"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7473_0c6d32bd5a50a7e5.jpg",
                "step": "10.最后把炒好的花生米一起翻炒"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7473_c4293ad0b1e5bf77.jpg",
                "step": "11.把酱油，盐，味精，糖，醋等调料搅拌均匀，并加适量水淀粉，烹入锅中，翻炒至汤汁收净即可"
            }]
        }, {
            "id": "7490",
            "title": "宫保鸡丁",
            "tags": "川菜;家常菜;咸香;10分钟内;宴请;朋友聚餐;1-2人;锅子;其他工艺",
            "imtro": "宫保鸡丁是我的最爱，是每次外出吃饭必点的一道菜，每个餐馆，每个厨师做的味道都不一样，我还是最喜欢峨眉酒家的宫保鸡丁，那个味道超赞，今天我也山寨一把，哈哈哈也不错呢。",
            "ingredients": "鸡腿肉,200g;花生米,50g",
            "burden": "大葱,适量;辣椒,4个;花椒,适量;胡椒粉,2g;料酒,1大勺;糖,1勺;醋,1勺;酱油,1勺;番茄酱,1勺;盐,2g;淀粉,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/8\/7490_188080.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_2a1282731b5c03c2.jpg",
                "step": "1.鸡大腿去骨切丁。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_62b167f0559735bf.jpg",
                "step": "2.鸡腿肉加入少许的盐 蛋清 白胡椒 料酒搅拌均匀。腌制20分钟。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_99533aeced85e864.jpg",
                "step": "3.大葱切丁，准备好辣椒 花椒。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_cb33d8739ec49cc3.jpg",
                "step": "4.取一碗放入淀粉，糖 酱油 醋 盐 水和少量的番茄酱勾兑成料汁。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_b856db85b22fd147.jpg",
                "step": "5.凉油下锅把花生米炸至酥香备用。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_d1ee1159c8e755d2.jpg",
                "step": "6.锅中放油。烧热。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_f9a7f17a15a65ef5.jpg",
                "step": "7.放入腌制好的鸡丁。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_6d4d747f9937e5a8.jpg",
                "step": "8.翻炒至肉色变白。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_2d9c6c6243747444.jpg",
                "step": "9.把炒至好的鸡丁成出备用。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_61efbb7b089dd26f.jpg",
                "step": "10.锅中留滴油，爆香辣椒 花椒。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_072c4cd6762b9f08.jpg",
                "step": "11.转小火，倒入碗汁。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_2ec2f84858834bd2.jpg",
                "step": "12.烧制汤汁浓缩。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_6fd5ff940385ef03.jpg",
                "step": "13.倒入鸡丁 花生米 葱段，翻炒。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7490_afb915ee08c05a55.jpg",
                "step": "14.翻炒均匀，收干汤汁即可。"
            }]
        }, {
            "id": "7498",
            "title": "宫保鸡丁",
            "tags": "川菜;甜;夏季;冬季",
            "imtro": "宫保鸡丁是甜辣口味，属于川菜。大家都很喜欢吃，做起来感觉不是很简单，不过查了很多资料，决定亲自试一试，没想到还蛮成功。",
            "ingredients": "鸡腿肉,300g;胡萝卜,50g;黄瓜,100g;葱,30g;尖椒,50g;花生,100g",
            "burden": "油,适量;盐,适量;蒜,适量;干辣椒,适量;糖,适量;醋,适量;料酒,适量;老抽,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/8\/7498_572120.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_ec06e04cb7db5677.jpg",
                "step": "1.准备好材料"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_642bc55530842857.jpg",
                "step": "2.都切成丁，备用"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_6570ab0fda75481f.jpg",
                "step": "3.花生泡水里容易去皮"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_4a1d2e68d1d450e7.jpg",
                "step": "4.去皮的花生"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_2b8aa9623eccfda8.jpg",
                "step": "5.放少许油，小火，不断翻炒花生"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_a1724d6bc36bf0e0.jpg",
                "step": "6.颜色变深究可以了，晾凉备用"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_4bb5d5ba4c9724f4.jpg",
                "step": "7.琵琶腿2个"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_ca1bc0b915f5d0fe.jpg",
                "step": "8.去骨去筋"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_15b0fe7abb36b4a9.jpg",
                "step": "9.切成小丁"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_28e40b3e5aa383da.jpg",
                "step": "10.用盐料酒腌一会"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_f6d0e8aaf26f9c26.jpg",
                "step": "11.蒜切片，干辣椒适量"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_272a08e64aa9a11c.jpg",
                "step": "12.下蒜辣椒炒鸡腿肉"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_3c887f39fad1676d.jpg",
                "step": "13.放入所有青菜配料"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_1f448143a0c51eaa.jpg",
                "step": "14.放花生炒匀"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/75\/7498_c21c71a96b1172c9.jpg",
                "step": "15.最后放事先调好的酱汁（糖，醋，老抽，盐，料酒）"
            }]
        }, {
            "id": "7510",
            "title": "宫保鸡丁",
            "tags": "川菜;家常菜;热菜;通乳;微辣;夏季;鲜香;催乳;下奶",
            "imtro": "宫保鸡丁 我在饭店吃过，当时觉的很好吃，就也在家试了。 上网搜过很多看了，觉的方法都差不多的，我就做了个简易版的 宫保鸡丁。 放的辣椒多了 有点辣，下次要改进下。",
            "ingredients": "鸡脯肉,300g;酒鬼花生,50g;豌豆,20g",
            "burden": "油,适量;盐,适量;红辣椒,适量;酱油,适量;淀粉,适量;五香粉,适量;料酒,适量;小葱,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/8\/7510_261264.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7510_22f29cf8a6464f7b.jpg",
                "step": "1.微波解冻"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7510_407c0a249f89f5d5.jpg",
                "step": "2.曾听人说过，这样的浅花刀可以能让肉肉入味儿些"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7510_e20ceb13cc0bb6a4.jpg",
                "step": "3.适量盐、酱油、淀粉、鸡精和五香粉，少许料酒搅拌后腌渍。。。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7510_de89e49bea764c75.jpg",
                "step": "4.红辣椒 、葱 备用"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7510_83954cfd27151e4f.jpg",
                "step": "5.酒鬼花生 和豌豆"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7510_651bb7bb0b129151.jpg",
                "step": "6.用十余粒花椒爆锅，不喜欢食用，挑出扔掉！肉丁入锅滑炒变色后加入干红椒"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7510_113fd0fbab65158b.jpg",
                "step": "7.炸出香昧儿后，加入葱段、青豆。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7510_07004b00871d3966.jpg",
                "step": "8.待肉丁和青豆完全熟后，加入甜红椒丁和花生米继续翻炒，淋入碗汁儿，出锅。"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7510_74bc7c251fc89de3.jpg",
                "step": "9.成品很香的哦。"
            }]
        }, {
            "id": "7513",
            "title": "宫保鸡丁",
            "tags": "川菜;家常菜;咸香;孕妇;冬季;孕晚期",
            "imtro": "鸡肉肉质细腻，利于产妇消化吸收。鸡肉具有温中益气，补精添髓，补虚益智的作用。《神农本草经》上说常吃鸡肉能通神，后世医家大多认为食之令人聪慧。因此孕妇应当多食用鸡肉制品，对胎儿的智力发育还有一定帮助。 宫保鸡丁是一款很营养又美味的家常菜，很多人都对此有着不同的青睐。此菜鸡肉鲜嫩，花生香脆，入口鲜辣，食之非常开胃。 在很多饭店，“宫保鸡丁”，常被写作“宫爆鸡丁”，时过境迁，很多人已经不知道“宫保”为何物。所谓“宫保”，原是其发明者丁宝桢的荣誉官衔。虽一字之差，但却改变了纪念丁保桢的初衷。 【营养价值及功效】 1鸡胸脯肉蛋白质含量较高，易被人体吸收入利用，有强身健体的作用。鸡胸脯肉含有的磷脂类，是人体生长发育的重要来源之一。鸡胸脯肉有益五脏，补虚损，补虚健胃、强筋壮骨、活血通络、调月经、止白带等作用。 2.花生含有维生素E和一定量的锌，能增强记忆，抗老化，延缓脑功能衰退，滋润皮肤；花生中的不饱和脂肪酸有降低胆固醇的作用，用助于防治动脉硬化、高血压和冠心病；花生中含有一种生物活性物质白藜芦醇可以防治肿瘤类疾病，同时也是降低血小板聚集，预防和治疗动脉粥样硬化、心脑血管疾病的化学预防剂；花生纤维组织中的可溶性纤维被人体消化吸收时，会像海绵一样吸收液体和其他物质，然后膨胀成胶带体随粪便排出体外，从而降低有害物质在体内的积存和所产生的毒性作用，减少肠癌发生的机会。 3.胡萝卜含有大量胡萝卜素，这种胡萝卜素的分子结构相当于2个分子的维生素A，进入机体后，在肝脏及小肠粘膜内经过酶的作用，其中50%变成维生素A，有补肝明目的作用；胡萝卜含有植物纤维，吸水性强，在肠道中体积容易膨胀，是肠道中的“充盈物质”，可加强肠道的蠕动，从而利膈宽肠，通便防癌；胡萝卜含有大量的维生素A，是骨骼正常生长发育的必需物质，有助于细胞增殖与生长，是机体生长的要素，对促进婴幼儿的生长发育具有重要意义；胡萝卜素转变成维生素A，有助于增强机体的免疫轼能，在预防上皮细胞癌变的过程中具有重要作用。胡萝卜中的木质素也能提高机体免疫机制，间接消灭癌细胞；胡萝卜还含有降糖物质，是糖尿病人的良好食品，其所含的某些成分，如懈皮素、山标酚能增加冠状动脉血流量，降低血脂，促进肾上腺素的合成，还有降压，强心作用，是高血压、冠心病患者的食疗佳品。",
            "ingredients": "鸡胸脯肉,1块;胡萝卜,1根;花生仁,1碗",
            "burden": "大葱,适量;姜,适量;干辣椒,适量;大蒜,适量;料酒,适量;生抽,适量;绵白糖,适量;淀粉,适量;醋,适量;鸡精,适量;精盐,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/8\/7513_701346.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_73bd4330c3d9421a.jpg",
                "step": "1.葱切段，胡萝卜切丁；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_53473388038d726f.jpg",
                "step": "2.姜切末，蒜去根切片，辣椒去籽掰碎；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_063a7ef8982e5bfa.jpg",
                "step": "3.鸡胸肉切丁，加入料酒，盐抓匀，腌制15分钟；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_8fdcefae0ca79e6b.jpg",
                "step": "4.生花生米，过油小火炸熟；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_2b58b59d3e841af7.jpg",
                "step": "5.盛出备用；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_575c7023bdf02fc9.jpg",
                "step": "6.调制芡汁：将白糖、生抽、料酒和淀粉各1勺，水2勺，醋3勺，盐和鸡精少许同入碗中，搅拌均匀；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_0f233af311a2f94b.jpg",
                "step": "7.锅中倒油，中火加热，下入胡萝卜翻炒几下；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_26bc1165e14aa9c0.jpg",
                "step": "8.再下入葱段继续翻炒；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_33fe1341fa298530.jpg",
                "step": "9.断生后盛出；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_091760b658c91d78.jpg",
                "step": "10.腌制好的鸡丁，加入少许淀粉和油抓匀；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_b632fc6314349a1c.jpg",
                "step": "11.趁热锅倒油，下入鸡丁翻炒；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_adffc7a08f3a7cf0.jpg",
                "step": "12.待鸡丁滑散断生后盛出；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_9aa8ab7d8ef8698f.jpg",
                "step": "13.趁热锅，下入姜、蒜、辣椒爆香；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_8631a83a0afce470.jpg",
                "step": "14.下鸡丁继续翻炒；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_ef3cb40750a91ec4.jpg",
                "step": "15.随后下入葱段和胡萝卜丁翻炒；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_f780b5731b844996.jpg",
                "step": "16.加入调好的芡汁，翻炒收浓；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_31f6f170625466d6.jpg",
                "step": "17.最后倒入花生米，掂炒几下即可关火；"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7513_d12b539221058edc.jpg",
                "step": "18.出锅装盘即可。"
            }]
        }, {
            "id": "7515",
            "title": "宫保鸡丁",
            "tags": "川菜;家常菜;炒;增强抵抗力;冬季菜谱",
            "imtro": "一直很喜欢馨怡的菜品，真是色香味俱全啊，每次看到都馋的我直流口水啊。这个宫保鸡丁就是跟她学习的。",
            "ingredients": "鸡胸肉,300g",
            "burden": "油,适量;盐,适量;白糖,适量;生抽,适量;葱,适量;姜,适量;蒜,适量;醋,适量;料酒,适量;花生仁,适量;干辣椒,适量;花椒,适量",
            "albums": ["http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/t\/8\/7515_271925.jpg"],
            "steps": [{
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_80920ed76a1449dc.jpg",
                "step": "1.准备花生仁，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_e7833b9976540630.jpg",
                "step": "2.干辣椒剪成小段，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_2a08299426e7c2c5.jpg",
                "step": "3.鸡胸肉拍松后切成丁，用盐生抽料酒和红薯淀粉拌匀上浆，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_59c93d413364d0ae.jpg",
                "step": "4.葱切成段，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_14f70c553a280ade.jpg",
                "step": "5.花生米入油锅炸脆，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_0218834f41156984.jpg",
                "step": "6.捞出晾凉，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_67b0e21939716858.jpg",
                "step": "7.调芡汁：白糖，盐，生抽，醋，红薯淀粉，分别倒在碗里调成汁备用，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_00490951401e020a.jpg",
                "step": "8.锅做热后倒凉油，迅速倒入鸡肉丁滑散，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_e95ab313bd673da1.jpg",
                "step": "9.炒至肉丁变色后盛出，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_4c1ca3d82908e571.jpg",
                "step": "10.锅里留少许的底油，下蒜和姜片炒香，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_14893690fabcfcdd.jpg",
                "step": "11.倒入干辣椒段炒，再下花椒炒，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_2a12fbce2ec52e3d.jpg",
                "step": "12.加入葱段，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_e75ae6f07f884f17.jpg",
                "step": "13.把炒好的鸡肉丁倒入锅中炒散，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_f096d20191326369.jpg",
                "step": "14.再下炒熟的花生米，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_7b8cf71b9c74280c.jpg",
                "step": "15.倒入芡汁，"
            }, {
                "img": "http:\/\/juheimg.oss-cn-hangzhou.aliyuncs.com\/cookbook\/s\/76\/7515_2034a66709af1b84.jpg",
                "step": "16.炒匀后迅速出锅装盘。"
            }]
        }],
        "totalNum": "67",
        "pn": 0,
        "rn": "20"
    },
    "error_code": 0
}